### ISSUE TITLE
Duplicate entry for abort code

### ISSUE THREAD

**Issue by borispovod** [movingco/move-ts#15]
Trying to do ts files for my module [U256](https://github.com/pontem-network/U256):

```sh
cargo install move-tsgen --features address32
move-tsgen -o ./ts
```

Getting error:

```json
{
  "error": "Duplicate entry for abort code 0 found in 43417434FD869EDEE76CCA2A4D2301E528A1551B1D719B75C350C3C97D15B8B9::u256, previous entry: ErrorDescription {\n    code_name: \"EQUAL\",\n    code_description: \"When both `U256` equal.\",\n}"
}
```

If i understood correctly it happens because i have two consts in my code contains same value, yet not all constants in the module are error codes, and some of them can have equal value for some error code in code.

**Comment by macalinao** [comment]
Should be fixed on crates.io
