### ISSUE TITLE
Type declaration issue in TypeScript

### ISSUE THREAD

**Issue by hodlen** [movingco/move-ts#4]
It seems that generated TS types embeds contract address into type name, which is invalid in terms of syntax. Like this:

```typescript
/** Struct representing the balance of each address. */
export type 0xcafe::BasicCoin::BalanceData = {
  coin: {
    value: p.U64;
  };
};

export type 0xcafe::BasicCoin::CoinData = {
  value: p.U64;
};
```

Generated from a small example here: https://github.com/move-language/move/tree/main/language/documentation/tutorial/step_4_sol/BasicCoin. It is a mere compilable coin module.

**Comment by macalinao** [comment]
fixed
